spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
